name: deploy

on:
  push:
    branches:
      - develop
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

env:
  # バージョン何が使えるのかは以下を参照
  # https://github.com/actions/node-versions/blob/main/versions-manifest.json
  node-version: '22.x'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      #
      # Setup for build
      #
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache_node_modules
        with:
          # キャッシュキー完全一致しない場合 yarn installする必要があるのでrestore-keysは使わない
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
          path: '**/node_modules'

      - name: Install Dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      #
      # Init
      #
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/vwbl-demo-stg-deploy-role
          aws-region: ap-northeast-1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable
      - name: node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
          path: '**/node_modules'
      #
      # Build & Deploy
      #
      - name: Build
        env:
          NEXT_PUBLIC_PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          NEXT_PUBLIC_ALCHEMY_NFT_API: ${{ secrets.ALCHEMY_NFT_API }}
          NEXT_PUBLIC_NFT_CONTRACT_ADDRESS: '0x54268b9d89582695c16D525fa6E94A16Cf6e5F37'
          NEXT_PUBLIC_VWBL_NETWORK_URL: https://dev.vwbl.network
          NEXT_PUBLIC_CHAIN_ID: '80002'
          NEXT_PUBLIC_LIGHT_HOUSE_KEY: ${{ secrets.LIGHT_HOUSE_KEY }}
          NEXT_PUBLIC_BICONOMY_API_KEY: ${{ secrets.BICONOMY_API_KEY }}
          NEXT_PUBLIC_MINT_API_ID: ${{ secrets.MINT_API_ID }}
          NEXT_PUBLIC_TRANSFER_API_ID: ${{ secrets.TRANSFER_API_ID }}
          NEXT_PUBLIC_INFURA_KEY: ${{ secrets.INFURA_KEY }}
          NEXT_PUBLIC_FORWARDER_ADDRESS: '0xd240234dacd7ffdca7e4effcf6c7190885d7e2f0'
          NEXT_PUBLIC_DATA_COLLECTOR_ADDRESS: '0xfe97f7137D19F107E952d6BD2877aDa43672D0D3'
          NEXT_PUBLIC_COMPANY_INFORMATION_KEY: ${{ secrets.COMPANY_INFORMATION_KEY }}
          NEXT_PUBLIC_COMPANY_INFORMATION_URL: 'https://gateway.lighthouse.storage/ipfs/QmR7GxwQYoptci6RyQthVftCHoJ7WkydWisUA2ynXUtbXo'
          NEXT_PUBLIC_BLOCKCHAIN_PARTY_KEY: ${{ secrets.BLOCKCHAIN_PARTY_KEY }}
          NEXT_PUBLIC_BLOCKCHAIN_PARTY_URL: 'https://gateway.lighthouse.storage/ipfs/QmWScRUXNf4PWU9ESYs6HCHkGSbhcU4JfWAS63BbLcdFFK'
          NEXT_PUBLIC_GACHA_NFT_CONTRACT_ADDRESS: ${{ secrets.GACHA_NFT_CONTRACT_ADDRESS }}
          NEXT_PUBLIC_GACHA_API_URL: ${{ secrets.GACHA_API_URL }}
          NEXT_PUBLIC_GACHA_TRANSFER_API_ID: ${{ secrets.GACHA_TRANSFER_API_ID }}
          NEXT_PUBLIC_GACHA_BICONOMY_API_KEY: ${{ secrets.GACHA_BICONOMY_API_KEY }}
          NEXT_PUBLIC_REOWN_ID: ${{ secrets.REOWN_ID }}
        run: |
          yarn build
      - name: Deploy to s3
        run: |
          aws s3 sync \
            --exact-timestamps \
            --delete \
            "out" s3://${{ secrets.DEPLOY_BUCKET }}
      - name: Clear cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"

  deploy-production:
    if: contains(github.ref, 'tags/v')
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      #
      # Init
      #
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/vwbl-demo-deploy-role
          aws-region: ap-northeast-1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable

      - name: node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
          path: '**/node_modules'
      #
      # Build & Deploy
      #
      - name: Build
        env:
          NEXT_PUBLIC_PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          NEXT_PUBLIC_ALCHEMY_NFT_API: ${{ secrets.ALCHEMY_NFT_API }}
          NEXT_PUBLIC_NFT_CONTRACT_ADDRESS: '0x42Dd5Ef4773aA438A668f02C5E26f0F31a5e994C'
          NEXT_PUBLIC_VWBL_NETWORK_URL: 'https://vwbl.network'
          NEXT_PUBLIC_CHAIN_ID: '137'
          NEXT_PUBLIC_LIGHT_HOUSE_KEY: ${{ secrets.LIGHT_HOUSE_KEY }}
          NEXT_PUBLIC_BICONOMY_API_KEY: ${{ secrets.BICONOMY_API_KEY }}
          NEXT_PUBLIC_MINT_API_ID: ${{ secrets.MINT_API_ID }}
          NEXT_PUBLIC_TRANSFER_API_ID: ${{ secrets.TRANSFER_API_ID }}
          NEXT_PUBLIC_INFURA_KEY: ${{ secrets.INFURA_KEY }}
          NEXT_PUBLIC_FORWARDER_ADDRESS: '0xf0511f123164602042ab2bCF02111fA5D3Fe97CD'
          NEXT_PUBLIC_DATA_COLLECTOR_ADDRESS: '0x707Fa219bE169e88208A4a177dcEBd504a468fD9'
          NEXT_PUBLIC_COMPANY_INFORMATION_KEY: ${{ secrets.COMPANY_INFORMATION_KEY }}
          NEXT_PUBLIC_COMPANY_INFORMATION_URL: 'https://gateway.lighthouse.storage/ipfs/QmR7GxwQYoptci6RyQthVftCHoJ7WkydWisUA2ynXUtbXo'
          NEXT_PUBLIC_BLOCKCHAIN_PARTY_KEY: ${{ secrets.BLOCKCHAIN_PARTY_KEY }}
          NEXT_PUBLIC_BLOCKCHAIN_PARTY_URL: 'https://gateway.lighthouse.storage/ipfs/QmWScRUXNf4PWU9ESYs6HCHkGSbhcU4JfWAS63BbLcdFFK'
          NEXT_PUBLIC_GACHA_NFT_CONTRACT_ADDRESS: ${{ secrets.GACHA_NFT_CONTRACT_ADDRESS }}
          NEXT_PUBLIC_GACHA_API_URL: ${{ secrets.GACHA_API_URL }}
          NEXT_PUBLIC_GACHA_TRANSFER_API_ID: ${{ secrets.GACHA_TRANSFER_API_ID }}
          NEXT_PUBLIC_GACHA_BICONOMY_API_KEY: ${{ secrets.GACHA_BICONOMY_API_KEY }}
          NEXT_PUBLIC_REOWN_ID: ${{ secrets.REOWN_ID }}
        run: |
          yarn build
      - name: Deploy to s3
        run: |
          aws s3 sync \
            --exact-timestamps \
            --delete \
            "out" s3://${{ secrets.DEPLOY_BUCKET }}
      - name: Clear cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
